#!/bin/sh
RICEBOXES=$HOME/.local/share/.riceboxes
SELECTED_BOX=ALPHA
AUR_MANAGER=trizen
EC_RED='\033[0;31m'
EC_YELLOW='\033[0;33m'
EC_GREEN='\033[0;32m'
EC_BLUE='\033[0;34m'
EC_NC='\033[0m'

check_internet(){
	if [ "$(ping -c 3 archlinux.org 2>&1 | tail -n 1 | grep rtt)" == "" ]; then
		echo false
	else
		echo true
	fi
}

clone_ricebox(){
	if [ "$1" == "" ];then
		name=$SELECTED_BOX"_"$RANDOM
		if [ ! -d "$RICEBOXES/$name" ];then
			cp -r $RICEBOXES/$SELECTED_BOX $RICEBOXES/$name
		else
			while [ ! -d "$RICEBOXES/$name" ];do
				name=$SELECTED_BOX"_"$RANDOM
			done
			cp -r $RICEBOXES/$SELECTED_BOX $RICEBOXES/$name
		fi
		echo $SELECTED_BOX cloned as $name
	else
		if [ ! -d "$RICEBOXES/$1" ];then
			cp -r $RICEBOXES/$SELECTED_BOX $RICEBOXES/$1
		else
			echo Error: $1 already exists
		fi
		echo $SELECTED_BOX cloned as $1
	fi
}

select_ricebox(){
	if [ "$1" == "" ];then
		ls -1 $RICEBOXES | grep -v MATRIX
		read -p "Name of the box to select?: " a
	else 
		a=$1
	fi
	[ -d "$RICEBOXES/$a" ] && sed -i 's/^SELECTED_BOX=.*$/SELECTED_BOX='$a'/' $HOME/.local/share/bin/rw
}

set_aur(){
	if [ "$1" == "" ];then
		read -p "Name of the AUR manager to use?: " a
	else 
		a=$1
	fi
	sed -i 's/^AUR_MANAGER=.*$/AUR_MANAGER='$a'/' $HOME/.local/share/bin/rw
}

create_new_ricebox(){
	if [ "$1" == "" ];then
		read -p "Name of the new box?: " a
		
	else
		a=$1
	fi
	mkdir $RICEBOXES/$a
	#TODO: Update Selected box
	select_ricebox $a
}

delete_ricebox(){
	if [ "$1" == "" ];then
		ls -1 $RICEBOXES | grep -v MATRIX
		read -p "Name of the box to delete?: " a
	else 
		a=$1
	fi
	rm -rf $RICEBOXES/$a
	select_ricebox $a
}

print_ricebox(){
	while read -r a;do
		box=`echo $a | sed 's,^.*/\(.*\)$,\1,'`
		#TODO: Box info
		if [ "$box" == "$SELECTED_BOX" ]; then
			echo "*" $box
		else
			echo $box
		fi
	done <<< $(find $RICEBOXES -maxdepth 1 -type d | tail -n +2)
}

list_box_items(){
	if [ "$1" == "m" ];then
		echo $SELECTED_BOX:
		find $RICEBOXES/$SELECTED_BOX/ -type d | tail -n +2 | sed 's,^.*/\(.*\)$,\1,'
		echo "###LINK MAP###"
		cat $RICEBOXES/$SELECTED_BOX/LinkMap
	elif [ "$1" == "i" ];then
		if [ "$2" == "" ];then
			while read -r a;do
				echo -n $SELECTED_BOX" -- "
				echo $a | sed 's,^.*/\(.*\)$,\1,'
				if [ -f $a/FileMap ];then
				       	echo FileMap: 
					while read -r b;do
						printf '\t'$b'\n'
					done <<< $( cat $a/FileMap )
				fi
				if [ -f $a/DepMap ];then
				       	echo DepMap: 
					while read -r b;do
						printf '\t'$b'\n'
					done <<< $( cat $a/DepMap )
				fi
				if [ -f $a/ExecMap ];then
				       	echo ExecMap: 
					while read -r b;do
						printf '\t'"$b"'\n'
					done <<< $( cat $a/ExecMap )
				fi
				if [ -d $a/Files ];then
					echo $(ls -1 $a/Files | wc -l) Files
				fi
			done <<< $(find $RICEBOXES/$SELECTED_BOX/ -type d | tail -n +2)
		else
			a=`find $RICEBOXES/$SELECTED_BOX/ -type d | tail -n +2 | grep $2`
			echo -n $SELECTED_BOX" -- "
			echo $a | sed 's,^.*/\(.*\)$,\1,'
			if [ -f $a/FileMap ];then
			       	echo FileMap: 
				while read -r b;do
					printf '\t'$b'\n'
				done <<< $( cat $a/FileMap )
			fi
			if [ -f $a/DepMap ];then
			       	echo DepMap: 
				while read -r b;do
					printf '\t'$b'\n'
				done <<< $( cat $a/DepMap )
			fi
			if [ -f $a/ExecMap ];then
			       	echo ExecMap: 
				while read -r b;do
					printf '\t'"$b"'\n'
				done <<< $( cat $a/ExecMap )
			fi
			if [ -d $a/Files ];then
				echo $(ls -1 $a/Files | wc -l) Files
			fi
		fi
	elif [ "$1" == "s" ];then
		while read -r a;do
			#a="$(echo $a | sed 's,^.*/\(.*\)$,\1,')"
			echo -n $a | sed 's,^.*/\(.*\)$,\1\t,'
			if [ -f $a/FileMap ];then
				echo -n "F:$(cat "$a"/FileMap | wc -l) "
			fi
			if [ -f $a/DepMap ];then
				echo -n "D:$(cat "$a"/DepMap | wc -l) "
			fi
			if [ -f $a/ExecMap ];then
				echo -n "E:$(cat "$a"/ExecMap | wc -l) "
			fi
			if [ -d $a/Files ];then
				echo $(ls -1 $a/Files | wc -l) Files
			fi
			if [ ! -d $a/Files ] && [ ! -f $a/ExecMap ] && [ ! -f $a/DepMap ] && [ ! -f $a/FileMap ];then
				echo !!! NC !!!!!
			else
				echo
			fi
		done <<< $(find $RICEBOXES/$SELECTED_BOX/ -type d | tail -n +2)
	else
		find $RICEBOXES/$SELECTED_BOX/ -type d | tail -n +2 | sed 's,^.*/\(.*\)$,\1,;s/\;.$//'
	fi
}

grab_full_item(){
	while read -r b; do
		if [ "$(echo $b | sed 's/\;.$//')" == "$1" ];then
			echo $b
		fi
	done <<< $(list_box_items m)
}

grab_full_dep(){
	if [ -f $RICEBOXES/$SELECTED_BOX/$1/DepMap ];then
		while read -r b;do
			if [ "$(echo $b | sed 's/\;.$//')" == "$2" ];then
				echo $b
			fi
		done <<< $( cat $RICEBOXES/$SELECTED_BOX/$1/DepMap )
	fi
}

remove_link(){
	to_remove=`echo $1 | sed 's/;[apn]$//'`
	while read -r a;do
		if [ ! "$(echo $a | grep -o "^.*$to_remove;[apn]$")" == "" ];then
			sed -i '/'$a'/d' $RICEBOXES/$SELECTED_BOX/LinkMap
		fi
	done <<< $(cat $RICEBOXES/$SELECTED_BOX/LinkMap)	
	
}

remove_orphaned_link(){
	to_remove=`echo $1 | sed 's/;[apn]$//'`
	while read -r a;do
		if [ ! "$(echo $a | grep -o "^*.*$to_remove;[apn]$")" == "" ];then
			sed -i '/'$a'/d' $RICEBOXES/$SELECTED_BOX/LinkMap
		fi
	done <<< $(cat $RICEBOXES/$SELECTED_BOX/LinkMap)	
	
}

parse_relpath(){
	echo $1 | sed 's,~,'$HOME','
}

write_gene(){
	while read -r b;do
		if [ "$b" == "FileMap" ];then
			echo Filemap Found
			mkdir $a/Files
			echo Files folder made
			while read -r c;do
				user_group=`echo $c | awk 'BEGIN { FS=";" } { print $1 }'`
				perms=`echo $c | awk 'BEGIN { FS=";" } { print $2 }'`
				map=`echo $c | awk 'BEGIN { FS=";" } { print $3 }'`
				file=`echo $map | awk 'BEGIN { FS="->" } { print $1 }'`
				dest=`echo $map | awk 'BEGIN { FS="->" } { print $2 }'`
				dest=`parse_relpath $dest`
				fp=$dest"/"$file
				echo $a/Files
				echo $fp
				if [ -d "$fp" ];then
					cp -ra "$fp" "$a/Files/"
				elif [ -f "$fp" ];then
					cp -a "$fp" "$a/Files/"
				else
					echo File $fp does not exists
				fi
			done <<< $(cat $a/FileMap)
		fi
	done <<< $(ls $1)
}

seal_ricebox(){
	if [ "$1" == "" ];then
		seal_ver=`date +%d%m%y_%s`
	else
		seal_ver="$1"
	fi
	old_sb=$SELECTED_BOX
	clone_ricebox $SELECTED_BOX"_"$seal_ver
	SELECTED_BOX=$SELECTED_BOX"_"$seal_ver
	echo $SELECTED_BOX
	while read -r a;do
		if [ ! "$a" == "" ];then
			write_gene $a
		fi
	done <<< $(find $RICEBOXES/$SELECTED_BOX -type d )
	if [ ! "$2" == "" ];then
		mv $RICEBOXES/$SELECTED_BOX "$2"
		echo Wrote Rice Genome to $2
	else
		mv $RICEBOXES/$SELECTED_BOX "$HOME"
		echo Wrote Rice Genome to $HOME
	fi
	select_ricebox $old_sb
}

parse_rice_command(){
	c=$1
	subc=`echo $2 | sed 's/^\(.\).*$/\1/'`
	subca=`echo $2 | sed 's/^.\(.*\)$/\1/'`
	if [ "$c" == "a" ];then
		if [ "$subc" == "i" ];then
			manager=`echo $subca | sed 's/^\(.\).*$/\1/'`
			install=`echo $subca | sed 's/^.\(.*\)$/\1/'`
			if [ "$manager" == "p" ];then
				if [ "$3" == "" ]; then
					read -p "Name of program to add?: " a
				else
					a=$3
				fi
				if [ "$install" == "y" ];then
					sudo pacman -S --noconfirm $a && mkdir $RICEBOXES/$SELECTED_BOX/$a\;$manager && echo *$a\;$manager >> $RICEBOXES/$SELECTED_BOX/LinkMap
				else
 					mkdir $RICEBOXES/$SELECTED_BOX/$a\;$manager && echo *$a\;$manager && echo *$a\;$manager >> $RICEBOXES/$SELECTED_BOX/LinkMap
				fi
			elif [ "$manager" == "a" ];then
				if [ "$3" == "" ]; then
					read -p "Name of program to add?: " a
				else
					a=$3
				fi
				if [ "$install" == "y" ];then
					$AUR_MANAGER --noconfirm -S $a && mkdir $RICEBOXES/$SELECTED_BOX/$a\;$manager && echo *$a\;$manager >> $RICEBOXES/$SELECTED_BOX/LinkMap
				else
					mkdir $RICEBOXES/$SELECTED_BOX/$a\;$manager && echo *$a\;$manager >> $RICEBOXES/$SELECTED_BOX/LinkMap
				fi
			elif [ "$manager" == "n" ];then
				if [ "$3" == "" ]; then
					read -p "Name of program to add?: " a
				else
					a=$3
				fi
				mkdir $RICEBOXES/$SELECTED_BOX/$a\;$manager && echo *$a\;$manager >> $RICEBOXES/$SELECTED_BOX/LinkMap
			fi
		elif [ "$subc" == "e" ];then
			if [ "$3" == "" ];then
				read -p "Item to add command to?: " a
				i=`grab_full_item $a`	
			else
				i=`grab_full_item $3`
			fi
			vim /tmp/execcmd
			t=`echo $subca | sed 's/^\(.\).*$/\1/'`
			e=`echo $subca | sed 's/^.\(.*\)$/\1/'`
			if [ -f "/tmp/execcmd" ];then
				while read -r a; do
					if [ "$t" == "p" ];then
						echo p\;$a >> $RICEBOXES/$SELECTED_BOX/$i/ExecMap
					elif [ "$t" == "i" ];then
						echo i\;$a >> $RICEBOXES/$SELECTED_BOX/$i/ExecMap
					elif [ "$t" == "P" ];then
						echo P\;$a >> $RICEBOXES/$SELECTED_BOX/$i/ExecMap
					fi
					if [ "$e" == "y" ];then
						$a
					fi
				done <<< $(cat /tmp/execcmd)
				rm /tmp/execcmd
			fi
		elif [ "$subc" == "f" ];then
			if [ "$3" == "" ];then
				list_box_items
				read -p "item to link file to: " a
				item=`grab_full_item $a`	
			else
				item=`grab_full_item $3`
			fi
			if [ "$4" == "" ];then
				read -p "origin filename: " b
			else
				a=$4
			fi
			if [ "$5" == "" ];then
				read -p "Destination folder: " c
			else
				b=$5
			fi
			if [ ! "$6" == "" ];then
				perm=$6
			else 
				perm=764
			fi
			if [ "$subca" == "r" ];then
				echo "root:root;$perm;$a->$b" >> $RICEBOXES/$SELECTED_BOX/$item/FileMap
			elif [ "$subca" == "u" ];then
				echo "USER:USER;$perm;$a->$b" >> $RICEBOXES/$SELECTED_BOX/$item/FileMap
			fi		
		elif [ "$subc" == "d" ];then
			manager=`echo $subca | sed 's/^\(.\).*$/\1/'`
			install=`echo $subca | sed 's/^.\(.*\)$/\1/'`

			if [ "$3" == "" ];then
				list_box_items
				read -p "item to add dep to?: " a
				item=`grab_full_item $a`	
			else
				item=`grab_full_item $3`
			fi
			if [ ! "$item" == "" ];then
				if [ "$4" == "" ];then
					read -p "Name of dep?: " b
					dep="$b"
				else
					dep="$4"
				fi
				echo "$dep;$manager" >> $RICEBOXES/$SELECTED_BOX/$item/DepMap
				if [ "$install" == "y" ];then
					sudo pacman --noconfirm -S $dep
				fi
			else
				[ "$a" == "" ] && echo $3 not found || echo $a not found
			fi
		fi
	elif [ "$c" == "e" ];then
		if [ "$subc" == "f" ];then
			if [ "$3" == "" ];then
				list_box_items
				read -p "Which Item's FileMap do you want to edit?: " a
				item=`grab_full_item $a`
			else
				item=`grab_full_item $3`
			fi
			vim $RICEBOXES/$SELECTED_BOX/$item/FileMap
		elif [ "$subc" == "e" ];then
			if [ "$3" == "" ];then
				list_box_items
				read -p "Which Item's ExecMap do you want to edit?: " a
				item=`grab_full_item $a`
			else
				item=`grab_full_item $3`
			fi
			vim $RICEBOXES/$SELECTED_BOX/$item/ExecMap
		elif [ "$subc" == "d" ];then
			if [ "$3" == "" ];then
				list_box_items
				read -p "Which Item's DepMap do you want to edit?: " a
				item=`grab_full_item $a`
			else
				item=`grab_full_item $3`
			fi
			vim $RICEBOXES/$SELECTED_BOX/$item/DepMap
		elif [ "$subc" == "n" ];then
			if [ "$subca" == "r" ];then
				read -p "New name for $SELECTED_BOX?: " a
				while [ -d "$RICEBOXES/$a" ];do
					read -p "$a already exists: " a
				done
				mv $RICEBOXES/$SELECTED_BOX $RICEBOXES/$a
				select_ricebox $a
			fi
		fi
	elif [ "$c" == "r" ];then
		uninstall=`echo $subca | sed 's/^.*\(.\)$/\1/'`
		if [ "$subc" == "i" ];then
			list_box_items
			if [ "$3" == "" ];then
				read -p "Item to remove?: " a
			else
				a=$3
			fi
			while read -r b; do
				if [ "$(echo $b | sed 's/\;.$//')" == "$a" ];then
					rm -rf $RICEBOXES/$SELECTED_BOX/$b
					if [ "$uninstall" == "y" ];then
					       sudo pacman -Rns --noconfirm $a
				       	fi	       
					remove_link $b
				fi
			done <<< $(list_box_items m)
		elif [ "$subc" == "d" ];then
			uninstall=`echo $subca | sed 's/^.*\(.\)$/\1/'`
			if [ "$3" == "" ];then
				list_box_items
				read -p "Item to remove dep from?: " a
				item=`grab_full_item $a`	
			else
				item=`grab_full_item $3`

			fi
			if [ -f $RICEBOXES/$SELECTED_BOX/$item/DepMap ];then
				while read -r b;do
					printf "$( echo $b | sed 's/\(.*\)\;[apn]$/\1/')"'\n'
				done <<< $( cat $RICEBOXES/$SELECTED_BOX/$item/DepMap )
			fi
			read -p "Dep to remove?: " a
			sed -i '/'"$a"'/d' $RICEBOXES/$SELECTED_BOX/$item/DepMap
			if ! grep -q '[^[:space:]]' < $RICEBOXES/$SELECTED_BOX/$item/DepMap;then
				rm $RICEBOXES/$SELECTED_BOX/$item/DepMap
			fi
		fi
	elif [ "$c" == "l" ];then
		if [ ! "$subc" == "b" ];then
			if [ "$subc" == "r" ];then
				if [ "$3" == "" ];then
					cat $RICEBOXES/$SELECTED_BOX/LinkMap | grep "*" 
					read -p "Item to link to Root?: " a
					item=`cat $RICEBOXES/$SELECTED_BOX/LinkMap | grep -o "*$a;[apn].*" | sed 's/*//g'`
				else
					item=`cat $RICEBOXES/$SELECTED_BOX/LinkMap | grep -o "*$3;[apn].*" | sed 's/*//g'`
				fi
				chain="R"
				newchain=`echo $chain::$item`
			else
				if [ "$3" == "" ];then
					cat $RICEBOXES/$SELECTED_BOX/LinkMap | grep -v "*" 
					read -p "Chain to link item to (last item in the chain)?: " a
					chain=`cat $RICEBOXES/$SELECTED_BOX/LinkMap | grep -o ".*$a;[apn]\$"`
				else
					chain=`cat $RICEBOXES/$SELECTED_BOX/LinkMap | grep -o ".*$3;[apn]\$"`
				fi
				echo "$chain"

				if [ "$4" == "" ];then
					cat $RICEBOXES/$SELECTED_BOX/LinkMap 
					read -p "Item to link?: " a
					item=`cat $RICEBOXES/$SELECTED_BOX/LinkMap | grep "$a" | sed 's/^*//g;s/^R.*::\(.*\;[apn]\)$/\1/g' | head -n 1`
				else
					item=`cat $RICEBOXES/$SELECTED_BOX/LinkMap | grep "$4" | sed 's/^*//g;s/^R.*::\(.*\;[apn]\)$/\1/g' | head -n 1`
				fi
				echo "$item has been set"
			fi
			if [ ! "$(echo "$item" | wc -l )" == "1" ];then
				echo $item is not 1!!!
			else
				if [ "$(echo "$chain")" == "1" ];then
					newchain=`echo $chain::$item`
					remove_orphaned_link $item
					echo $newchain >> $RICEBOXES/$SELECTED_BOX/LinkMap
				else
					while read -r a; do
						newchain=`echo $a::$item`
						echo $newchain >> $RICEBOXES/$SELECTED_BOX/LinkMap
					done <<<$(echo "$chain")
					remove_orphaned_link $item
				fi
			fi
			sort $RICEBOXES/$SELECTED_BOX/LinkMap >> $RICEBOXES/$SELECTED_BOX/LinkMapTMP
			rm $RICEBOXES/$SELECTED_BOX/LinkMap
			cp $RICEBOXES/$SELECTED_BOX/LinkMapTMP $RICEBOXES/$SELECTED_BOX/LinkMap
			rm $RICEBOXES/$SELECTED_BOX/LinkMapTMP
		else
			if [ "$3" == "" ];then
				cat $RICEBOXES/$SELECTED_BOX/LinkMap 
				read -p "Item to break at (Between it and it's parent)?: " a
				breakpoint=`cat $RICEBOXES/$SELECTED_BOX/LinkMap | grep -o ".*$a;[apn].*"`
			else
				breakpoint=`cat $RICEBOXES/$SELECTED_BOX/LinkMap | grep -o ".*$3;[apn].*"`
			fi
			while read -r b;do
				sed -i '/'$b'/d' $RICEBOXES/$SELECTED_BOX/LinkMap 
				echo $b | sed 's/^R::.*\('$3'\;[apn].*\)/*\1/' >> $RICEBOXES/$SELECTED_BOX/LinkMap 
			done <<< $( echo "$breakpoint" )
			cp $RICEBOXES/$SELECTED_BOX/LinkMap $RICEBOXES/$SELECTED_BOX/LinkMapTmp
			rm -rf $RICEBOXES/$SELECTED_BOX/LinkMap 
			cat $RICEBOXES/$SELECTED_BOX/LinkMapTmp | uniq > $RICEBOXES/$SELECTED_BOX/LinkMap
		fi
	fi
}

release_locks(){
	sed -i "s/^"$2"::\(.*\)$/\1/" $1
}

has_parent(){
	[ "$(echo $1 | sed 's/^\(.\+\)'$2'.*$/\1/;s/^'$2'.*//')" == "" ] && echo false || echo true
}

check_chains(){
	to_process="true"
	while read -r a;do
		if [ "$(has_parent $a $2)" == "true" ];then
			to_process="false"
		fi
	done <<< $(cat $1 | grep $2)
	echo $to_process
}

lone_chain(){
	[ "$(echo $1 | awk 'BEGIN { FS="::" } { print NF }')" == "1" ] && echo true || echo false
}

update_linkmap(){
	sed -i 's/^'$2'::\(.*\)/\1/;/^'$2'$/d' $1
	sed -i '/[[:space:]].*/d' $1
}
get_item_m(){
	echo "$1" | awk 'BEGIN { FS=";" } { print $2 }'
}
get_item_n(){
	echo "$1" | awk 'BEGIN { FS=";" } { print $1 }'
}
em_has_ic(){
	if [ "$(cat $1/ExecMap | grep -e "^i;")" == "" ];then
		echo false
	else
		echo true
	fi
}

install(){
	p="$(get_item_n "$1")"
	manager="$(get_item_m "$1")"
	echo INSTALLING $p USING $manager
	if [ "$manager" == "a" ];then
		$AUR_MANAGER --sudo-autorepeat-at-runtime --noconfirm -S $p
	elif [ "$manager" == "p" ];then
		sudo pacman --noconfirm -S $p
	fi
}

parse_ug(){
	echo "$1" | sed 's/USER/'`whoami`'/g'
}

parse_dst(){
	echo "$1" | sed 's,~,'$HOME','
}


move_file(){
	UG="$(echo $2 | awk 'BEGIN { FS=";" } { print $1 }')"
	PERMS="$(echo $2 | awk 'BEGIN { FS=";" } { print $2 }')"
	FNDEST="$(echo $2 | awk 'BEGIN { FS=";" } { print $3 }')"
	FN="$(echo $FNDEST | awk 'BEGIN { FS="->" } { print $1 }')"
	DEST="$(echo $FNDEST | awk 'BEGIN { FS="->" } { print $2 }')"
	echo MOVING $FN from $1/Files/ to $DEST using User and group `parse_ug $UG` and with perms $PERMS
	[ ! -d "`parse_dst "$DEST"`" ] && mkdir -p `parse_dst "$DEST"` 
	sudo mv $1/Files/$FN `parse_dst "$DEST"`
	sudo chown `parse_ug $UG` `parse_dst "$DEST"`/$FN
	sudo chmod "$PERMS" `parse_dst "$DEST"`/$FN
}

depgrow(){
	while read -r a;do
		install $a
	done <<< $(cat $1/DepMap)
}
filegrow(){
	while read -r a;do
		move_file $1 $a
	done <<< $(cat $1/FileMap)
}
comgrow(){
	[ "$2" == "p" ] && n="Pre"
	[ "$2" == "i" ] && n="Init"
	[ "$2" == "P" ] && n="Post"
	while read -r a;do
		[ ! "$a" == "" ] && echo "$a" | sed 's/^[ipP]\;//g;s,~,'$HOME',g' >> $1/ExecMap_$n
	done <<< $(cat $1/ExecMap | grep -e "^$2;")
	[ -f "$1/ExecMap_$n" ] && sudo chmod +x $1/ExecMap_$n && /bin/sh $1/ExecMap_$n
}

process_item(){
	ipath=`echo $1 | sed 's/LinkMap//'`
	echo -e $EC_RED PROCESSING $2 $EC_NC
	EM_PRE="false"
	EM_INIT="false"
	EM_POST="false"
	DM_PROCESSED="false"
	FM_PROCESSED="false"
	INSTALLED="false"
	#PROCESS EXEC_PRE (IF EXISTING)
	#PROCESS DEPS (IF EXISTING)
	#INSTALL ITEM/PROCESS EXEC_INIT if exsisting
	#PROCESS FILES (IF EXISTING)
	#PROCESS EXEC_POST (IF EXISTING)

	if [ -f "$ipath$2/ExecMap" ];then
		echo -e $EC_YELLOW EXECUTTING COMMANDS $EC_NC
		comgrow "$ipath$2" "p"
		EM_PRE="true"
	elif [ -f "$ipath$2/DepMap" ];then
		echo -e $EC_YELLOW INSTALLING DEPENDENCIES $EC_NC
		depgrow "$ipath$2"
		DM_PROCESSED="true"
	else
		if [ ! "$(get_item_m "$2")" == "n" ]; then
			echo -e $EC_BLUE PRECONFIGURATION DONE, INSTALLING $2 $EC_NC
			install $2
		elif [ -f "$ipath$2/ExecMap" ] && [ "$(em_has_ic "$ipath$2")" == "true" ];then
			echo -e PRECONFIGURATION DONE, INSTALLING $2
			comgrow "$ipath$2" "i"
		else
			echo -e $EC_BLUE PRECONFIGURATION DONE, AND NO NEED TO INSTALL `get_item_n $2` $EC_NC
		fi
		INSTALLED="true"
	fi

	if [ -f "$ipath$2/DepMap" ] && [ ! "$DM_PROCESSED" == "true" ] ;then
		echo -e $EC_YELLOW INSTALLING DEPENDENCIES $EC_NC
		depgrow "$ipath$2"
		DM_PROCESSED="true"
	fi

	if [ ! "$(get_item_m "$2")" == "n" ] && [ "$INSTALLED" == "false" ]; then
		echo -e $EC_BLUE PRECONFIGURATION DONE, INSTALLING `get_item_n "$2"` $EC_NC
		install $2
	elif [ -f "$ipath$2/ExecMap" ] && [ "$(em_has_ic "$ipath$2")" == "true" ] && [ "$INSTALLED" == "false" ];then
		echo -e $EC_BLUE PRECONFIGURATION DONE, INSTALLING `get_item_n "$2"` $EC_NC
		comgrow "$ipath$2" "i"
	elif [ "$INSTALLED" == "false" ];then
		echo -e $EC_BLUE PRECONFIGURATION DONE, AND NO NEED TO INSTALL `get_item_n $2` $EC_NC
	fi

	if [ -f "$ipath$2/FileMap" ] && [ ! "$FM_PROCESSED" == "true" ];then
		echo -e $EC_YELLOW INSTALLING FILES $EC_NC
		filegrow "$ipath$2"
		FM_PROCESSED="true"
	fi
	
	if [ -f "$ipath$2/ExecMap" ];then
		comgrow "$ipath$2" "P"
	fi
	
	echo -e $EC_GREEN PROCESSED! $EC_NC
}

#gets chains that have no parentsa (and therefore ready for processing
process_chains(){
	#cat $1 | grep -v -e "^A::" -e "^R::"
	#check if there are chains to process
	while [ ! "$(cat $1 | grep -v -e "^A::" -e "^R::" | wc -l)" == "0" ];do
		#if there are, loop through them
		processed="false"
		processed_i=""
		while read -r a;do
			#if the current line is a lone chain, there are no other chains similar with a parent and nothing has been processed, process it and set processed to true
			if [ "$processed" == "false" ] && [ "$(lone_chain $a)" == "true" ] && [ "$(check_chains $1 $a)" == "true" ];then
				processed_i="$a"
				process_item $1 $a
				processed="true"
			fi
		done <<< $(cat $1 | grep -v -e "^A::" -e "^R::")
		[ "$processed" == "true" ] && update_linkmap $1 $processed_i
		#[ "$processed" == "true" ] && echo UPDATING NEWLY PROCESSED $processed_i
	done
}

incubate_rice(){
	if [ "$1" == "" ];then
		echo No rice to incubate, select a written rice genome folder
	else
		if [ -d "$1" ];then
			if [ -f "$1/LinkMap" ];then
				if [ "$(check_internet)" == "true" ];then
					release_locks "$HOME/$1LinkMap" "A"
					process_chains "$HOME/$1LinkMap"
					release_locks "$HOME/$1LinkMap" "R"
					process_chains "$HOME/$1LinkMap"
				else
					echo Please connect to the internet
				fi
				#RELEASE R LOCK
				#PROCESS CHAINS
				#process_aur_chains $1
				#	sed -i 's/R::\(.*\)/\1/' "$1/LinkMap"
				#	while [ ! "$(wc -l "$1/LinkMap")" == "0" ];do
				#		rs=`check_schains $1`
				#		echo RESOLVING $rs
				#		#resolve_gene $rs
				#		update_linkmap $1 "$rs"
				#	done
			else
				echo Genome Missing LinkMap, aborting.
			fi
		fi
	fi
}

parseArgs(){
	if [ "$1" == "new" ];then
		create_new_ricebox $2
	elif [ "$1" == "select" ];then
		select_ricebox $2
	elif [ "$1" == "print" ];then
		print_ricebox
	elif [ "$1" == "clone" ];then
		clone_ricebox $2
	elif [ "$1" == "delete" ];then
		delete_ricebox 
	elif [ "$1" == "info" ];then
		if [ ! "$2" == "" ];then
			list_box_items $2  $3
		else
			list_box_items m
		fi
	elif [ "$1" == "setaur" ];then
		set_aur $2
	elif [ "$1" == "seal" ];then
		seal_ricebox $2
	elif [ "$1" == "incubate" ];then
		incubate_rice $2
	elif [ ! "$(echo $1 | grep -v -e "print" -e "select" -e "delete" -e "new" -e "clone" )" == "" ];then
		#RICEBOX COMMANDS
		#e: edit
			#n: name
				#r: ricebox
				#i: item
			#e: ExecMap
			#d: Depmap
			#f: FileMap
		#a: add
			#e: exec
				#p: pre
					#y
				#P: post
					#y
				#i: init
					#y
			#f: file
				#r: root owned file
				#u: user owned file
			#i: item
				#p: pacman
					#y
				#a: aur
					#y
				#n: none
			#d: dependecy
				#p: pacman
					#y
				#a: aur
					#y
				#n: none
				
		#r: remove
			#f: file
			#i: item
			#d: dependency
		#l: link
			#r: Link to root
			#b: break chain
		c=`echo $1 | sed 's/^\([aerl]\).*$/\1/'`
		ca=`echo $1 | sed 's/^[aerl]\(.*\)$/\1/'`
		if [ ! "$ca" == "" ];then
			parse_rice_command $c $ca $2 $3 $4 $5
		else
			parse_rice_command $c "-" $2 $3 $4 $5
		fi
	fi
}

parseArgs $@
